### ISSUE TITLE
White wingpanel and font

### ISSUE THREAD

**Issue by varlesh** [crutchcorn/eXGTK#25] opened 2015-04-21 18:38 UTC
Wingpanel have white background and font, font not have shadow
![2015-04-21 21 36 44](https://cloud.githubusercontent.com/assets/8083855/7259831/b9db9966-e86e-11e4-8205-64db75210544.png)

**Comment by Defman21** [comment] 2015-04-21 18:39
Duplicate of #1

**Closed by Defman21** 2015-04-21 18:39 UTC
Labels: duplicate
