### ISSUE TITLE
Scrollbar color hardly distinguible

### ISSUE THREAD

**Issue by robby14** [crutchcorn/eXGTK#6] opened 2015-04-17 11:49 UTC
The first is from elementary and the latter from xgtk, in xgtk the scrollbar have a color not very distinguible.
![screenshot from 2015-04-17 12 20 55](https://cloud.githubusercontent.com/assets/11992666/7201518/60fe1bde-e508-11e4-9eb5-6471fc9ad0e8.png)
![screenshot from 2015-04-17 12 18 37](https://cloud.githubusercontent.com/assets/11992666/7201517/60fcefd4-e508-11e4-89a4-96b7d779d92c.png)

**Comment by crutchcorn** [comment] 2015-04-17 11:51
This seems to be a duplicate of #2. Please comment if it is not.

**Closed by crutchcorn** 2015-04-17 11:51 UTC

**Comment by robby14** [comment] 2015-04-17 12:00
oh sorry xD there are so less issues and I've already been able to make a duplicate xD. I'll pay more attention

**Comment by crutchcorn** [comment] 2015-04-17 12:01
Come off it mate, it's not a problem! :)
